### PR TITLE
Change default branch from master to main

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
The CI failure looks unrelated.

This might cause some issues downstream with

- The benchmark machine pulling the repo and running these nightly
- the asv tool
- the timeseries at https://pandas.pydata.org/speed/dask/

That's fine if we break things, it might just be a bit before I can get them fixed.

**Comment by jsignell** [comment]
Ok thanks for bringing that up.

**Comment by jakirkham** [comment]
Power cycling for CI

**Comment by jakirkham** [comment]
Merged and renamed the branch after

CI didn't run before the rename, but after the rename is [now running]( https://dev.azure.com/dask-dev/dask/_build/results?buildId=2259&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9 )

**Pull request merged**
