### PR TITLE
Have asv exit with non-zero status on benchmark failure

### LINKED ISSUE #25: Fail CI on failing benchmarks
The CI passed for https://github.com/dask/dask-benchmarks/pull/24, despite some benchmarks failing.

### PR DESCRIPTION
**Pull request by jrbourbeau**
Closes #25

### CODE REVIEW

**Comment by jrbourbeau** [comment]
CI fails...hooray?

**Comment by TomAugspurger** [comment]
A good first step!

**Comment by jrbourbeau** [comment]
This warning seems to be related to the failures we're seeing: `RuntimeWarning: coroutine 'BaseTCPListener.start' was never awaited`. Benchmarks pass with the following changes:

```diff
diff --git a/distributed/benchmarks/comm.py b/distributed/benchmarks/comm.py
index e1e98ed..ed520f8 100644
--- a/distributed/benchmarks/comm.py
+++ b/distributed/benchmarks/comm.py
@@ -77,7 +77,7 @@ class Connect(object):
     @gen.coroutine
     def _main(self, address):
         listener = listen(address, self._handle_comm)
-        listener.start()
+        yield listener.start()
         yield [self._connect_close(listener.contact_address)
                for i in range(self.N_CONNECTS)]
         listener.stop()
@@ -135,7 +135,7 @@ class Transfer(object):
     @gen.coroutine
     def _main(self, address, obj, n_transfers, **kwargs):
         listener = listen(address, partial(self._handle_comm, n_transfers), **kwargs)
-        listener.start()
+        yield listener.start()
         comm = yield connect(listener.contact_address, **kwargs)
         for i in range(n_transfers):
             yield comm.write(obj)
```

Is `yield listener.start()` the proper way to await it from within a tornado coroutine? It looks a little off to me

**Comment by TomAugspurger** [comment]
Yep, that should do it.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
